<?php
// $Id: uc_2checkout.install,v 1.1.2.4 2010/07/12 01:57:43 tr Exp $

/**
 * @file
 * Install file for uc_2checkout.module.
 */

/**
 * Implements hook_uninstall().
 */
function uc_paytm_uninstall() {
  // TODO Please review the conversion of this statement to the D7 database API syntax.
  /* db_query("DELETE FROM {variable} WHERE name LIKE 'uc_paytm_%%'") */
  db_delete('variable')
  ->condition('name', 'uc_paytm_%%', 'LIKE')
  ->execute();
}
